name: Linux CI
on:
  workflow_dispatch:
  workflow_call:

env:
  HAXE_VERSION: 4.3.7

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y gcc-i686-linux-gnu g++-i686-linux-gnu libdrm-dev:i386 libgl1-mesa-dev:i386 libglu1-mesa-dev:i386 libpulse-dev:i386 libasound2-dev:i386 libx11-dev:i386 libxext-dev:i386 libxi-dev:i386 libxrandr-dev:i386 libxinerama-dev:i386 libpng-dev:i386 libturbojpeg-dev:i386 libuv1-dev:i386 libvorbis-dev:i386 libgl1-mesa-dev libglu1-mesa-dev libpulse-dev libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev libmbedtls-dev libpng-dev libturbojpeg-dev libuv1-dev libvorbis-dev --no-install-recommends --no-install-suggests
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}
      - name: Set HAXEPATH
        run: echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV
      - name: Install Haxe dependencies
        run: |
          haxelib git hxcpp https://github.com/ShadowEngineTeam/hxcpp --quiet
          haxelib git format https://github.com/HaxeFoundation/format 9d69fb342d030fa120d2deafafbbffad248332b8 --quiet
          haxelib git hxp https://github.com/openfl/hxp 47ef5ae6569cb0961761a2fbb416694df067124c --quiet
      - name: Enable HXCPP compile cache
        run: echo "HXCPP_COMPILE_CACHE=~/.hxcpp" >> $GITHUB_ENV
      - name: Configure Lime
        run: haxelib dev lime ${{ github.workspace }}
      - name: Rebuild Lime
        run: |
          CC=i686-linux-gnu-gcc CXX=i686-linux-gnu-g++ linux32 haxelib run lime rebuild linux -32 -release -nocolor -nocffi -D HXCPP_M32
          haxelib run lime rebuild linux -64 -release -nocolor -nocffi
      - name: Upload Artifact (x86)
        uses: actions/upload-artifact@v4
        with:
          name: Linux-NDLL
          path: |
            ndll/Linux/
            !**/.gitignore
            lime.png
          if-no-files-found: error
      - name: Upload Artifact (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: Linux64-NDLL
          path: |
            ndll/Linux64/
            !**/.gitignore
            lime.png
          if-no-files-found: error
